# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - go mod tidy
universal_binaries:
  - replace: true
builds:
  - main: ./cmd/kcplens
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.CommitDate}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
      - goos: darwin
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
      - Goreleaser
      - Dockerfile
      - CI
      - '^test:'

sboms:
  - artifacts: archive

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    dependencies:
      - "bash"
    maintainer: "Peter Teich <mail@peter-teich.de>"
    vendor: "Peter Teich"
    homepage: "https://github.com/pteich/kcplens"
    description: "TUI for viewing Kubernetes CRDs and CRs."
    license: "MIT"

dockers:
  - image_templates: ["ghcr.io/pteich/kcplens:{{ .Version }}"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/pteich/kcplens
      - --label=org.opencontainers.image.source=https://github.com/pteich/kcplens
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

brews:
  - name: kcplens
    homepage: https://github.com/pteich/kcplens
    repository:
      owner: pteich
      name: homebrew-tap

scoops:
  - repository:
      owner: pteich
      name: scoop-bucket
    homepage: "https://github.com/pteich/kcplens"
    description: "TUI for viewing KCP workspaces and resources."
    license: "MIT"

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true